### ISSUE TITLE
User id & Password

### ISSUE THREAD

**Issue by neeld2025** [dk-mushiyoke/FederalTapHouse2#2]
Hello,
How do you generate user id & password for the app so that you can login??

Thanks
Neel

**Comment by dk-mushiyoke** [comment]
Hello @neeld2025, this was a course project that me and a couple of other people created a few years back. Note that it is not a functional app and the entire backend was filled with test data. Feel free to check out http://www.softwaremerchant.com/onlinecourse.asmx, there is an operation for creating a user.
